// <auto-generated>
// Generated by Live Cursor from Midnight.cursorset, Twinkle.cursorset.
// Changes to this file are overwritten when a cursor set is imported.
// </auto-generated>
using System.Collections.Generic;
using Opportunv.LiveCursor;

namespace Opportunv.LiveCursor.Samples
{
    public static class DemoCursorStates
    {
        public static readonly CursorStateId Default = new("Default");
        public static readonly CursorStateId Pointer = new("Pointer");
        public static readonly CursorStateId Text = new("Text");
        public static readonly CursorStateId Busy = new("Busy");
        public static readonly CursorStateId Blocked = new("Blocked");
        public static readonly CursorStateId Grab = new("Grab");
        public static readonly CursorStateId Grabbing = new("Grabbing");
        public static readonly CursorStateId Crosshair = new("Crosshair");

        public static readonly IReadOnlyList<CursorStateId> All = new[] { Default, Pointer, Text, Busy, Blocked, Grab, Grabbing, Crosshair };
    }
}
