"""Renders the Asset Store key images from the demo cursor frames.

Usage: python asset_store_images.py [output_folder]
Default output folder: Tools/Branding/AssetStore (relative to the repository root).
Writes icon.png (160x160), card.png (420x280), cover.png (1950x1300) and social.png (1200x630).
Requires Pillow and the frames generated by Tools/DemoCursors/generate.py.
"""
import glob
import os
import sys

from PIL import Image, ImageDraw

from social_preview import BACKGROUND_BOTTOM, BACKGROUND_TOP, STATES, SUBTITLE, TITLE, first_frame, font

TITLE_COLOR = (250, 250, 255)
SUBTITLE_COLOR = (185, 195, 215)
SKINS = [("Twinkle", (255, 255, 255, 22)), ("Midnight", (110, 140, 190, 60))]


def background(width, height):
    image = Image.new("RGBA", (width, height))
    draw = ImageDraw.Draw(image)
    for y in range(height):
        t = y / (height - 1)
        color = tuple(int(BACKGROUND_TOP[i] + (BACKGROUND_BOTTOM[i] - BACKGROUND_TOP[i]) * t) for i in range(3))
        draw.line([(0, y), (width, y)], fill=color + (255,))
    return image


def scaled(frame, size):
    return frame if frame.width == size else frame.resize((size, size), Image.LANCZOS)


def tile(image, frame, x, y, cell, tint):
    pad = max(2, cell // 32)
    tiles = Image.new("RGBA", image.size, (0, 0, 0, 0))
    ImageDraw.Draw(tiles).rounded_rectangle(
        [x - pad, y - pad, x + cell + pad, y + cell + pad], radius=cell * 18 // 128, fill=tint)
    image.alpha_composite(tiles)
    image.alpha_composite(scaled(frame, cell), (x, y))


def state_row(image, cursors, skin, tint, states, top, cell, gap):
    width = len(states) * cell + (len(states) - 1) * gap
    left = (image.width - width) // 2
    for index, state in enumerate(states):
        tile(image, first_frame(os.path.join(cursors, skin), state), left + index * (cell + gap), top, cell, tint)


def transition_frames(cursors, skin, name):
    folder = os.path.join(cursors, skin, "Transitions", name)
    return [Image.open(path).convert("RGBA") for path in sorted(glob.glob(os.path.join(folder, "*.png")))]


def icon(cursors):
    image = background(160, 160)
    image.alpha_composite(scaled(first_frame(os.path.join(cursors, "Twinkle"), "Default"), 160), (8, 6))
    return image


def card(cursors):
    image = background(420, 280)
    draw = ImageDraw.Draw(image)
    draw.text((210, 72), TITLE, font=font(54, True), fill=TITLE_COLOR, anchor="mm")
    states = ["Default", "Pointer", "Busy", "Grab"]
    state_row(image, cursors, "Twinkle", SKINS[0][1], states, 128, 80, 14)
    return image


def cover(cursors):
    image = background(1950, 1300)
    draw = ImageDraw.Draw(image)
    draw.text((975, 225), TITLE, font=font(156, True), fill=TITLE_COLOR, anchor="mm")
    draw.text((975, 345), SUBTITLE, font=font(60), fill=SUBTITLE_COLOR, anchor="mm")
    for row, (skin, tint) in enumerate(SKINS):
        state_row(image, cursors, skin, tint, STATES, 445 + row * 200, 168, 24)

    draw.text((975, 915), "Transitions play forwards, backwards and turn around mid-way", font=font(44),
              fill=SUBTITLE_COLOR, anchor="mm")
    frames = transition_frames(cursors, "Twinkle", "DefaultToPointer")
    cell, gap = 144, 64
    width = len(frames) * cell + (len(frames) - 1) * gap
    left = (image.width - width) // 2
    top = 995
    for index, frame in enumerate(frames):
        x = left + index * (cell + gap)
        tile(image, frame, x, top, cell, SKINS[0][1])
        if index < len(frames) - 1:
            arrow_x = x + cell + gap // 2
            draw.text((arrow_x, top + cell // 2), "›", font=font(64, True), fill=SUBTITLE_COLOR, anchor="mm")
    return image


def social(cursors):
    image = background(1200, 630)
    draw = ImageDraw.Draw(image)
    draw.text((600, 140), TITLE, font=font(92, True), fill=TITLE_COLOR, anchor="mm")
    draw.text((600, 220), SUBTITLE, font=font(36), fill=SUBTITLE_COLOR, anchor="mm")
    for row, (skin, tint) in enumerate(SKINS):
        state_row(image, cursors, skin, tint, STATES, 290 + row * 150, 120, 16)
    return image


def main():
    repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    cursors = os.path.join(repo, "Assets", "LiveCursorSamples", "Demo", "Cursors")
    output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo, "Tools", "Branding", "AssetStore")
    os.makedirs(output, exist_ok=True)
    for name, render in [("icon", icon), ("card", card), ("cover", cover), ("social", social)]:
        path = os.path.join(output, f"{name}.png")
        render(cursors).convert("RGB").save(path)
        print(path)


if __name__ == "__main__":
    main()
