"""Renders the repository's social preview image (1280x640) from the demo cursor frames.

Usage: python social_preview.py [output_path]
Requires Pillow and the frames generated by Tools/DemoCursors/generate.py.
"""
import glob
import os
import sys

from PIL import Image, ImageDraw, ImageFont

WIDTH, HEIGHT = 1280, 640
BACKGROUND_TOP = (40, 48, 68)
BACKGROUND_BOTTOM = (24, 28, 42)
TITLE = "Live Cursor"
SUBTITLE = "Animated hardware cursors for Unity"
STATES = ["Default", "Pointer", "Text", "Busy", "Blocked", "Grab", "Grabbing", "Crosshair"]


def first_frame(skin_folder, state):
    folder = os.path.join(skin_folder, "Idle", state)
    if os.path.isdir(folder):
        return Image.open(sorted(glob.glob(os.path.join(folder, "*.png")))[0]).convert("RGBA")
    sheet = Image.open(glob.glob(os.path.join(skin_folder, "Idle", f"{state}_*.png"))[0]).convert("RGBA")
    return sheet.crop((0, 0, 128, 128))


def font(size, bold=False):
    names = [
        "segoeuib.ttf" if bold else "segoeui.ttf",
        "arialbd.ttf" if bold else "arial.ttf",
        "LiberationSans-Bold.ttf" if bold else "LiberationSans-Regular.ttf",
    ]
    for name in names:
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def main():
    repo = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    cursors = os.path.join(repo, "Assets", "LiveCursorSamples", "Demo", "Cursors")
    output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo, "Tools", "Branding", "social-preview.png")

    image = Image.new("RGBA", (WIDTH, HEIGHT))
    draw = ImageDraw.Draw(image)
    for y in range(HEIGHT):
        t = y / (HEIGHT - 1)
        color = tuple(int(BACKGROUND_TOP[i] + (BACKGROUND_BOTTOM[i] - BACKGROUND_TOP[i]) * t) for i in range(3))
        draw.line([(0, y), (WIDTH, y)], fill=color + (255,))

    title_font = font(96, True)
    subtitle_font = font(38)
    draw.text((WIDTH / 2, 150), TITLE, font=title_font, fill=(250, 250, 255), anchor="mm")
    draw.text((WIDTH / 2, 232), SUBTITLE, font=subtitle_font, fill=(185, 195, 215), anchor="mm")

    cell = 128
    gap = 18
    row_width = len(STATES) * cell + (len(STATES) - 1) * gap
    left = (WIDTH - row_width) // 2
    tiles = Image.new("RGBA", (WIDTH, HEIGHT), (0, 0, 0, 0))
    tile_draw = ImageDraw.Draw(tiles)
    rows = [("Twinkle", 300, (255, 255, 255, 22)), ("Midnight", 450, (110, 140, 190, 60))]
    for skin, top, tint in rows:
        for index in range(len(STATES)):
            x = left + index * (cell + gap)
            tile_draw.rounded_rectangle([x - 4, top - 4, x + cell + 4, top + cell + 4], radius=18, fill=tint)
    image.alpha_composite(tiles)

    for skin, top, _ in rows:
        for index, state in enumerate(STATES):
            frame = first_frame(os.path.join(cursors, skin), state)
            image.alpha_composite(frame, (left + index * (cell + gap), top))

    image.convert("RGB").save(output)
    print(output)


if __name__ == "__main__":
    main()
