using System.Collections.Generic;
using System.Text;

namespace Opportunv.LiveCursor.Editor
{
    internal static class CursorStateCodeGenerator
    {
        private static readonly HashSet<string> _keywords = new()
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const",
            "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit",
            "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
            "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out",
            "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try",
            "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile",
            "while"
        };

        public static string Generate(string className, string @namespace, IReadOnlyList<string> stateNames,
            IReadOnlyList<string> sources)
        {
            StringBuilder builder = new();
            builder.Append("// <auto-generated>\n");
            builder.Append("// Generated by Live Cursor from ").Append(string.Join(", ", sources)).Append(".\n");
            builder.Append("// Changes to this file are overwritten when a cursor set is imported.\n");
            builder.Append("// </auto-generated>\n");
            builder.Append("using Opportunv.LiveCursor;\n\n");

            var indent = string.Empty;
            if (!string.IsNullOrEmpty(@namespace))
            {
                builder.Append("namespace ").Append(@namespace).Append("\n{\n");
                indent = "    ";
            }

            builder.Append(indent).Append("public static class ").Append(className).Append('\n');
            builder.Append(indent).Append("{\n");

            HashSet<string> usedIdentifiers = new();
            foreach (var stateName in stateNames)
            {
                var identifier = ToIdentifier(stateName);
                var unique = identifier;
                var suffix = 2;
                while (!usedIdentifiers.Add(unique) || unique == className)
                {
                    unique = $"{identifier}{suffix++}";
                }

                builder.Append(indent).Append("    public static readonly CursorStateId ").Append(unique)
                    .Append(" = new(\"").Append(Escape(stateName)).Append("\");\n");
            }

            builder.Append(indent).Append("}\n");
            if (indent.Length > 0)
            {
                builder.Append("}\n");
            }

            return builder.ToString();
        }

        public static string ToIdentifier(string name)
        {
            StringBuilder builder = new();
            var upperNext = true;
            foreach (var chr in name ?? string.Empty)
            {
                if (!char.IsLetterOrDigit(chr) && chr != '_')
                {
                    upperNext = true;
                    continue;
                }

                builder.Append(upperNext ? char.ToUpperInvariant(chr) : chr);
                upperNext = false;
            }

            if (builder.Length == 0)
            {
                return "_";
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, '_');
            }

            var identifier = builder.ToString();
            return _keywords.Contains(identifier) ? $"@{identifier}" : identifier;
        }

        public static bool IsValidIdentifier(string value)
        {
            if (string.IsNullOrEmpty(value) || _keywords.Contains(value))
            {
                return false;
            }

            if (!char.IsLetter(value[0]) && value[0] != '_')
            {
                return false;
            }

            foreach (var chr in value)
            {
                if (!char.IsLetterOrDigit(chr) && chr != '_')
                {
                    return false;
                }
            }

            return true;
        }

        public static bool IsValidNamespace(string value)
        {
            foreach (var part in value.Split('.'))
            {
                if (!IsValidIdentifier(part))
                {
                    return false;
                }
            }

            return true;
        }

        private static string Escape(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
